# Generated by Django 2.2.26 on 2022-05-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
