# Generated by Django 2.2.26 on 2022-05-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogStore', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=3, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='likesCount',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='viewCount',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
