# Generated by Django 2.2.26 on 2022-05-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogStore', '0004_auto_20220515_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='post',
            name='likesCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='viewCount',
            field=models.IntegerField(null=True),
        ),
    ]
