# Generated by Django 2.2.26 on 2022-05-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogStore', '0007_auto_20220515_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commentCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='likeCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='non', upload_to='images'),
        ),
    ]
