# Generated by Django 2.2.26 on 2022-05-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogStore', '0008_auto_20220515_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commentCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to='images'),
        ),
    ]
