# Generated by Django 2.2.26 on 2022-05-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogStore', '0010_post_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.CharField(max_length=255),
        ),
    ]
