# Generated by Django 2.2.26 on 2022-05-15 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogStore', '0011_auto_20220515_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desc',
            new_name='description',
        ),
    ]
